### ISSUE TITLE
Support manual configuration

### ISSUE THREAD

**Issue by aidan-plenert-macdonald** [connelhooley/react-oidc#4]
It looks like you are making requests to `/.well-known/openid-configuration`. I couldn't find where in your code, but I would like to add support for manually specifying the various endpoints like authorization, token, userinfo, etc. AWS Cognito does not have the `.well-known` endpoints, so I would need to configure the [Cognito endpoints](https://docs.aws.amazon.com/cognito/latest/developerguide/cognito-userpools-server-contract-reference.html) manually.

Can you briefly explain how I could add this support to your library (assuming you are willing to take a PR :) )? I couldn't find references [in your code](https://github.com/connelhooley/react-oidc/search?q=openid-configuration&type=Code)

**Comment by tostringtheory** [comment]
@aidan-plenert-macdonald - I'm not the maintainer, but a follower.  

You didn't find the openid-configuration specified in this plugin, because this plugin doesn't do any of the oidc work itself:

> A few opinionated React components wrapping *oidc-client* using the Hooks API.

What you're looking for is the `oidcSettings` prop on the `AuthProvider` component, which is then passed to the oidc-client `UserManager`:

From the source component: https://github.com/connelhooley/react-oidc/blob/f3be2e6ce9e3646aa2feceb9003c74c7fed747e5/src/AuthProvider.tsx#L39

Which then passes it to the `UserManager`:  https://github.com/connelhooley/react-oidc/blob/f3be2e6ce9e3646aa2feceb9003c74c7fed747e5/src/AuthService.ts#L18

The docs for that library are here - [oidc-client-js](https://github.com/IdentityModel/oidc-client-js/wiki).  Specifically, it looks like you'll want this section, which shows how to set the endpoints without the introspection endpoint - [Provider settings if CORS not supported on OIDC/OAuth2 provider metadata endpoint](https://github.com/IdentityModel/oidc-client-js/wiki#provider-settings-if-cors-not-supported-on-oidcoauth2-provider-metadata-endpoint)

Hope that helps!

**Comment by aidan-plenert-macdonald** [comment]
Perfect. Thank you
